export const users = [
  {
    _id: '66a2bd7dfd064cd0e96f23c5',
    index: 0,
    guid: '3f969cfc-79c6-4b8b-9f89-02f139578686',
    isActive: true,
    balance: '$3,760.17',
    picture: 'http://placehold.it/32x32',
    age: 21,
    eyeColor: 'brown',
    name: 'Dawson Shannon',
    gender: 'male',
    company: 'UTARA',
    email: 'dawsonshannon@utara.com',
    phone: '+1 (932) 593-3180',
    address: '951 Covert Street, Wheatfields, Virginia, 1520',
    about:
      'Ipsum cillum ullamco ullamco Lorem aute pariatur eiusmod incididunt enim consequat. Labore reprehenderit labore enim nisi pariatur laborum labore cupidatat. Ad veniam tempor anim in labore esse ullamco fugiat velit dolore anim non. Enim id nulla incididunt commodo mollit. Ipsum amet nulla eiusmod magna et magna. Nisi sit sunt proident in duis id nisi incididunt. Laboris excepteur minim elit officia tempor proident cupidatat in.\r\n',
    registered: '2016-02-01T12:39:44 -03:00',
    latitude: -28.553062,
    longitude: -136.11535,
    tags: ['et', 'velit', 'anim', 'magna', 'do', 'duis', 'incididunt'],
    friends: [
      {
        id: 0,
        name: 'Dale Fry',
      },
      {
        id: 1,
        name: 'Noble Rowland',
      },
      {
        id: 2,
        name: 'Joy Bond',
      },
    ],
    greeting: 'Hello, Dawson Shannon! You have 4 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '66a2bd7ddc5d317c6c302eaa',
    index: 1,
    guid: 'ec36b1ca-e3fb-478c-a9ca-87082736a34d',
    isActive: false,
    balance: '$3,678.76',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'brown',
    name: 'Elsa Campbell',
    gender: 'female',
    company: 'TERASCAPE',
    email: 'elsacampbell@terascape.com',
    phone: '+1 (911) 412-2371',
    address: '173 Hicks Street, Tonopah, Nevada, 1264',
    about:
      'Sunt quis irure nisi esse ipsum non aliqua Lorem commodo minim culpa in commodo labore. Aute adipisicing dolor exercitation in deserunt pariatur anim velit laborum proident eu Lorem nulla. Veniam velit mollit pariatur est reprehenderit aliquip quis dolore dolore nisi. Ex eiusmod nulla eu tempor pariatur cillum enim. Proident quis dolore culpa non ea et. Labore amet sit ipsum occaecat pariatur.\r\n',
    registered: '2022-09-11T10:45:25 -03:00',
    latitude: -78.450988,
    longitude: -26.232362,
    tags: ['fugiat', 'id', 'non', 'et', 'ad', 'quis', 'commodo'],
    friends: [
      {
        id: 0,
        name: 'Ellis Ashley',
      },
      {
        id: 1,
        name: 'Lakisha Bender',
      },
      {
        id: 2,
        name: 'Salinas Weiss',
      },
    ],
    greeting: 'Hello, Elsa Campbell! You have 3 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66a2bd7dd76b620bf40ac70a',
    index: 2,
    guid: '99ba4517-db76-4889-8dbc-bbe2aadde588',
    isActive: false,
    balance: '$3,310.32',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'brown',
    name: 'Maritza Aguilar',
    gender: 'female',
    company: 'DIGIAL',
    email: 'maritzaaguilar@digial.com',
    phone: '+1 (815) 415-3546',
    address: '731 Bliss Terrace, Sandston, South Carolina, 8545',
    about:
      'Anim laborum eu cupidatat amet dolor Lorem irure excepteur dolor dolor ut ea dolore do. Lorem laborum id nisi minim reprehenderit anim laborum fugiat minim nostrud quis commodo. Proident exercitation ea incididunt labore id id veniam id mollit laborum. Reprehenderit eu amet anim pariatur non deserunt dolore voluptate officia ea sit consectetur. Dolor adipisicing ullamco ad deserunt qui occaecat minim ad cupidatat quis officia. Elit enim do proident quis in enim eu. Cillum ea in aliqua adipisicing reprehenderit non sit.\r\n',
    registered: '2017-02-13T07:50:51 -03:00',
    latitude: -88.156194,
    longitude: -36.737159,
    tags: ['sint', 'veniam', 'proident', 'fugiat', 'dolor', 'proident', 'est'],
    friends: [
      {
        id: 0,
        name: 'Shelby Daugherty',
      },
      {
        id: 1,
        name: 'Coffey Trujillo',
      },
      {
        id: 2,
        name: 'Hodges Owens',
      },
    ],
    greeting: 'Hello, Maritza Aguilar! You have 7 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66a2bd7da5afae03d51f307e',
    index: 3,
    guid: '493a2327-a267-4220-8ab4-df2f9c0fc94d',
    isActive: false,
    balance: '$1,303.30',
    picture: 'http://placehold.it/32x32',
    age: 29,
    eyeColor: 'blue',
    name: 'Logan Coleman',
    gender: 'male',
    company: 'ZILLACTIC',
    email: 'logancoleman@zillactic.com',
    phone: '+1 (969) 412-3358',
    address: '840 Empire Boulevard, Lodoga, Wisconsin, 7781',
    about:
      'Nostrud mollit irure ex deserunt veniam laboris ut amet id ex eu amet. Amet aute est nisi ullamco officia et cupidatat eu minim enim. Anim aute dolor ipsum ut esse eu velit ea laboris fugiat et anim.\r\n',
    registered: '2023-08-25T08:30:44 -03:00',
    latitude: 6.831145,
    longitude: 86.765551,
    tags: [
      'adipisicing',
      'pariatur',
      'occaecat',
      'non',
      'duis',
      'irure',
      'aliqua',
    ],
    friends: [
      {
        id: 0,
        name: 'Jenkins Wood',
      },
      {
        id: 1,
        name: 'Luna Buckley',
      },
      {
        id: 2,
        name: 'Ernestine Beck',
      },
    ],
    greeting: 'Hello, Logan Coleman! You have 2 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '66a2bd7dd35d3badcfc121b8',
    index: 4,
    guid: 'adfaf912-c13f-424c-a4cc-38e2960f5b53',
    isActive: true,
    balance: '$3,295.25',
    picture: 'http://placehold.it/32x32',
    age: 27,
    eyeColor: 'brown',
    name: 'James Blair',
    gender: 'female',
    company: 'OATFARM',
    email: 'jamesblair@oatfarm.com',
    phone: '+1 (888) 409-2507',
    address: '774 Allen Avenue, Staples, Mississippi, 6828',
    about:
      'Laborum labore duis et irure est aute eiusmod consectetur excepteur quis consequat duis minim et. Fugiat et cupidatat ad ea sit veniam. Exercitation aute commodo mollit non esse et. Pariatur magna reprehenderit aliquip eiusmod ad magna laboris voluptate aliqua enim tempor.\r\n',
    registered: '2020-02-17T06:09:13 -03:00',
    latitude: -86.689695,
    longitude: 106.914283,
    tags: ['culpa', 'adipisicing', 'elit', 'ipsum', 'elit', 'veniam', 'ipsum'],
    friends: [
      {
        id: 0,
        name: 'Shauna Gates',
      },
      {
        id: 1,
        name: 'Barnes Bowers',
      },
      {
        id: 2,
        name: 'Parsons Roach',
      },
    ],
    greeting: 'Hello, James Blair! You have 4 unread messages.',
    favoriteFruit: 'strawberry',
  },
];
